import type { Metadata } from "next";
import "./globals.css";
import VisitorTracker from "@/components/analytics/VisitorTracker";
import SiteHeaderWrapper from "@/components/storefront/site-header-wrapper";
import { SHOP_NAME } from "./constants";

export const metadata: Metadata = {
  title: SHOP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <VisitorTracker />

        <SiteHeaderWrapper />

        <main className="pt-16">
          {children}
        </main>
      </body>
    </html>
  );
}
