import type { Metadata } from "next";

import "./globals.css";

import VisitorTracker from "@/components/analytics/VisitorTracker";
import { ImageKitProvider } from "@/components/providers/imagekit-provider";
import SiteHeaderWrapper from "@/components/storefront/site-header-wrapper";
import { createServiceRoleClient } from "@/lib/supabase/service-role";

import { SHOP_NAME } from "./constants";

export const metadata: Metadata = {
  title: SHOP_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: LayoutProps<"/">) {
  const supabase =
    createServiceRoleClient();

  const { data: settings } =
    await supabase
      .from("site_settings")
      .select("imagekit_enabled")
      .eq("id", true)
      .single();

  const imageKitEnabled =
    settings?.imagekit_enabled !== false;

  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <ImageKitProvider
          enabled={imageKitEnabled}
        >
          <VisitorTracker />

          <SiteHeaderWrapper />

          <main className="pt-16">
            {children}
          </main>
        </ImageKitProvider>
      </body>
    </html>
  );
}