import type { Metadata } from "next";
import "./globals.css";
import VisitorTracker from "@/components/analytics/VisitorTracker";

export const metadata: Metadata = {
  title: "Lucky Charm Creations",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col"><VisitorTracker />{children}</body>
    </html>
  );
}
